### ISSUE TITLE
宏定义问题

### ISSUE THREAD

**Issue by iStig** [li6185377/IMYHiveMind#1]
// 完整的绑定方法，可调整优先级
//#define IMYHIVE_BIND_CLASS_INTACT($class, $protocol, $singleton, $priority, $iscls) _imy_hive_bind_impl("bind", $protocol, $class, $priority, $singleton, $iscls, _imy_hive_func_register_name())

应该调整下  $priority 和 $singleton参数位置吧
调整后
#define IMYHIVE_BIND_CLASS_INTACT($class, $protocol, $priority, $singleton, $iscls) _imy_hive_bind_impl("bind", $protocol, $class, $priority, $singleton, $iscls, _imy_hive_func_register_name())

**Comment by li6185377** [comment]
看了下 其实是 IMYHIVE_BIND_CLASS 传参到 IMYHIVE_BIND_CLASS_INTACT 参数顺序错了，已修改：https://github.com/li6185377/IMYHiveMind/commit/1bab746fd3a3455ea3b4bef56b90d448c600735a
